### ISSUE TITLE
thinkplot.brewer throwing exception in dungeons.py

### ISSUE THREAD

**Issue by vedmathai** [AllenDowney/ThinkBayes#11]
If dungeons.py is run as is an exception
>Traceback (most recent call last):
>  File "dungeons.py", line 117, in <module>
>    main()
>  File "dungeons.py", line 63, in main
>    colors = thinkplot.Brewer.Colors()
>AttributeError: 'module' object has no attribute 'Brewer'

is thrown. I think line 63 should be thinkplot._Brewer.Colors().
It works then, however I am not sure what is it exactly you intend in terms of the single underscore - weakly hidden method.

**Comment by AllenDowney** [comment]
Should be fixed with commit 6df885bc82fcc28c73714a35db17fdbc5e766504

Thanks for letting me know!

**Comment by vedmathai** [comment]
cool, thanks!
